# Generated by Django 4.1 on 2022-08-21 17:03

import digletweb.users.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="default_avatar.png",
                upload_to=digletweb.users.models.user_directory_path,
            ),
        ),
    ]
