# Generated by Django 4.1 on 2022-08-21 17:34

from django.db import migrations, models

import digletweb.users.models
import digletweb.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="background_image",
            field=models.ImageField(
                blank=True,
                upload_to=digletweb.users.models.profile_background_directory_path,
                validators=[digletweb.users.validators.background_image_restriction],
            ),
        ),
    ]
