# Generated by Django 4.1 on 2022-08-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_about_user_facebook_profile_user_fullname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="fullname",
            new_name="full_name",
        ),
    ]
