# Generated by Django 4.1 on 2022-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_alter_link_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="num_vote_down",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="link",
            name="num_vote_up",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="link",
            name="vote_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
