# Generated by Django 4.1 on 2022-08-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0004_relatedlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedlink",
            name="domain",
            field=models.URLField(blank=True),
        ),
    ]
