# Generated by Django 4.1 on 2022-08-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0005_alter_relatedlink_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedlink",
            name="parent",
            field=models.ForeignKey(
                default=6, on_delete=django.db.models.deletion.CASCADE, to="links.link"
            ),
            preserve_default=False,
        ),
    ]
